name: Glaive
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7226543857250363
title: Project GLAIVE devblog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#66564d'
    - '#dfc582'
    - '#541f24'
    - '#c3894e'
  brandStrength: 0.8252312219701707
  lightness: 0.5530849196948111
  saturation: 0.4794467242900282
  rhythmicContrast: 0.5
purpose: []
